### ISSUE TITLE
[Minor] Window can be resized while on splash

### ISSUE THREAD

**Issue by pipe01** [JimmyCushnie/TUNG#11]
This is a really minor bug, but I thought it won't hurt if I report it. The title says it all, the window can be resized normally while on the Mouse Hat Games logo splash scene, while it cannot be resized inside the game itself.

**Comment by JimmyCushnie** [comment]
Thanks for reporting this. I just tested it, and from what I can see the game window _is_ resizable after the splash screen, but the cursor only changes to arrows during the splash screen. Video to show you what I'm talking about: https://youtu.be/GPhhTOf1eTU

Is this what you're experiencing as well?

**Comment by pipe01** [comment]
Oh, I didn't realize you could actually resize it in-game too, my bad.
