### ISSUE TITLE
The placement of "through" components is handled inconsistently

### ISSUE THREAD

**Issue by Shaolin-Funk** [JimmyCushnie/TUNG#12]
Version: 0.1.4

![illegal](https://user-images.githubusercontent.com/35553599/35224859-63234e1e-ff7e-11e7-8191-0ca41d166596.png)

The above screenshot shows 5 different components mounted on a board, which is itself also mounted on a board. 

The game allows you to place the components and interact with them normally. However if you remove the green board and try to remount it in the same place, it sees that the components would collide and refuses to let you place it.

**Comment by Shaolin-Funk** [comment]
![also illegal](https://user-images.githubusercontent.com/35553599/35225398-23ff8246-ff80-11e7-97fc-855c99da63e4.png)

Actually I just realised it's not only through components. Here's an inverter colliding with a peg. Placing the components like this is fine, but again if you remove the green board it won't let you place it back in the same position.

![very illegal](https://user-images.githubusercontent.com/35553599/35225711-f3b342a2-ff80-11e7-9e48-8e9b8e09b3f8.png)

You can take this further and have two components occupying mostly the same space.

**Comment by JimmyCushnie** [comment]
Yeah the rules for placing stuff are... pretty lax at the moment. This will be improved in 0.2
