### ISSUE TITLE
missing pegs on ui and ingame

### ISSUE THREAD

**Issue by bluziDev** [JimmyCushnie/TUNG#13]
game stuttering every half second. reload world and pegs were missing.

**Comment by JimmyCushnie** [comment]
[This](https://drive.google.com/open?id=1ab-AEaFlP6Fr0CaoAeSeLoCvCgtFA03W) is the save file you sent in PMs (reposting here for posterity). When I opened it everything was normal. 
![2018-01-22 15_15_41z](https://user-images.githubusercontent.com/32693298/35242344-4c96c7c6-ff87-11e7-885a-4cd77eb7c681.png)
![2018-01-22 15_15_36z](https://user-images.githubusercontent.com/32693298/35242345-4ca422ea-ff87-11e7-862f-c71a1ea52c9b.png)

What were you doing that caused this? Can you recreate it?

**Comment by bluziDev** [comment]
it happens to blotters and inverters with no wire attached to the peg. i think it just makes them invisible because i tried connecting a peg to where the peg on an inverter would be and it worked and the peg popped into visibility.

**Comment by JimmyCushnie** [comment]
Do you know what makes it happen to those components?

**Comment by JimmyCushnie** [comment]
probably fixed in 0.2
