### ISSUE TITLE
flying bug

### ISSUE THREAD

**Issue by bluziDev** [JimmyCushnie/TUNG#17]
flying can't be turned on while running. not sure if bug. edit: nvm i think it's because i have flight speed bound to shift+b. i wouldn't want that to happen anyway

**Comment by JimmyCushnie** [comment]
Cannot reproduce. However, by default, the run key is the same as the key for fly down, so if you press B while holding Shift you'll get pushed into the ground and it won't seem like you're flying. Is that it?

**Comment by JimmyCushnie** [comment]
Can the issue be closed?
