### ISSUE TITLE
Problem with Launcher Windowed setting

### ISSUE THREAD

**Issue by 512bits** [JimmyCushnie/TUNG#18]
The launcher has a checkbox option, Windowed, which doesn't seem to work. It starts the game according to this setting, but it quickly changes to the setting currently under options inside the game.

I'm on Windows 10 playing v 0.2.1.

**Comment by Iamsodarncool** [comment]
I agree that this kind of sucks, but the alternative is to not have the checkbox in the options menu. Unity doesn't let you remove stuff from the launcher. Eventually I want to have in-game menus for everything in the launcher (keybindings, resolution, graphics API) and once I have that I'll disable the launcher entirely.

**Comment by JimmyCushnie** [comment]
Will fix, thank you.

**Comment by JimmyCushnie** [comment]
fixed in 0.2.2
