### ISSUE TITLE
Snapping pegs not always snapping

### ISSUE THREAD

**Issue by Stenodyon** [JimmyCushnie/TUNG#20]
In [this world](https://drive.google.com/open?id=1l6mHJ4sp48qjWHzTlVAiw5iJYssLtmJ_) some snapping pegs don't snap together even after save/reload.

![What it looks like](https://i.imgur.com/h28hKSM.jpg)

**Comment by Stenodyon** [comment]
Steps to reproduce an instance of the bug:

- Create a new world
- Place a 1x2 board on a 1x4 plate to create a height difference
- Place snapping pegs facing each-other

![What you end up with](https://i.imgur.com/6Ucx0oj.jpg)

**Comment by JimmyCushnie** [comment]
The bug was actually that they ever snapped at all; snapping pegs shouldn't snap over height differences like that. Fixed in 0.2.2

**Comment by Stenodyon** [comment]
Ah I had read your message on discord wrong and thought they were supposed to connect
