### ISSUE TITLE
Issues with F2 help menu displaying offset

### ISSUE THREAD

**Issue by Vykori** [JimmyCushnie/TUNG#22]
TUNG 0.2.2
issue described in detail in this video https://youtu.be/cPEv8fPsW4w

you can recreate this bug by pressing F1 to hide the cursor, pressing F2 to bring up the help menu, even though it's hidden, and pressing F1 again to bring your HUD back up. the help menu will now be shown (at least on my monitor, 2560x1440 pixels, full screen in TUNG) incorrectly

**Comment by JimmyCushnie** [comment]
Turns out a proper fix for this one is really hard, so for 0.2.3 F1 no longer affects the help menu.
