### ISSUE TITLE
snapping pegs

### ISSUE THREAD

**Issue by bluziDev** [JimmyCushnie/TUNG#24]
1. sometimes can't connect to regular peg on a copy of a board
2. turn invisible when you click on them?
3. should keep the rotation of last placed

**Comment by JimmyCushnie** [comment]
1. cannot reproduce, if you have more specific instructions for making it happen that'd be extremely helpful
2. ditto
3. press R to toggle rotation lock

**Comment by JimmyCushnie** [comment]
Ah, 1. and 2. were probably fixed in 0.2.5
