### ISSUE TITLE
Visual artifacts in boards

### ISSUE THREAD

**Issue by chrizzz** [JimmyCushnie/TUNG#28]
https://youtu.be/HegcP4YWqXk

**Comment by JimmyCushnie** [comment]
Does this happen with all boards all the time or only with some? Do any of the graphics settings affect it? What is your graphics card?

**Comment by chrizzz** [comment]
Yes this happens with all boards all the time. My settings are as follows: https://i.imgur.com/4jKoKUW.jpg
I'm playing at 1440p on a GTX 970.

There are two settings that seem to affect it.
The first one is vsync; off doesn't make it any better, but double buffered makes it a lot worse than single buffered.
Turning on motion blur significantly improves the situation, but I don't really like motion blur.

**Comment by chrizzz** [comment]
Here's a video with all the 6 different combination between Vsync and motion blur:
https://www.youtube.com/watch?v=GXpttr4xOkI

**Comment by chrizzz** [comment]
This can be resolved by turning MFAA off in the NVidia control panel: https://i.imgur.com/iyNzS4P.png
