### ISSUE TITLE
Snapping pegs refuse valid connection

### ISSUE THREAD

**Issue by Vykori** [JimmyCushnie/TUNG#31]
using TUNG 0.2.4, with pitung and sharemod added

steps to recreate:
create board A
create board B, attached to board A
connect board A to B with snapping pegs
connect snapping peg on board A to anything also placed on board A
clone board A (this clones both boards)
delete whatever snapping peg A was connected to
place something new for snapping peg A to connect to, you cannot connect them together

**Comment by chrizzz** [comment]
Confirmed for vanilla 0.2.4
https://www.youtube.com/watch?v=1COqhb-XZU0

**Comment by JimmyCushnie** [comment]
Fixed for 0.2.5. Thank you so much @NikWillOrStuff  for the detailed instructions and @chrizzz for the video! Made diagnosing the bug a breeze 😎
