### ISSUE TITLE
Common Unity Jump Input Bug

### ISSUE THREAD

**Issue by ForLoveOfCats** [JimmyCushnie/TUNG#32]
**Game Version:** 0.2.4
**OS:** Manjaro GNU/Linux x64 w/ Plasma 5
**Mods or Addons:** None

TUNG suffers from a bug common in Unity games where pressing the jump input key while midair causes the player to jump again once landed. While not a rather big issue this is unexpected behavior that should be corrected.

Cheers!

**Comment by JimmyCushnie** [comment]
In 0.2.5 (not out yet) you must now hit jump 0.2 seconds before you hit the ground or less. This value can be changed in settings.txt under "JumpTiming"
