### ISSUE TITLE
Blotters ignore player's rotation when placed

### ISSUE THREAD

**Issue by pipe01** [JimmyCushnie/TUNG#5]
When you place components such as inverters and switches, their rotation depends on the player's rotation, but this isn't the case with blotters.

**Comment by pipe01** [comment]
Wait nevermind I'm mentally challenged.

**Comment by JimmyCushnie** [comment]
lol

**Comment by JimmyCushnie** [comment]
did you have rotation lock on?

**Comment by pipe01** [comment]
...maybe
