### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Shaolin-Funk** [JimmyCushnie/TUNG#9]
[crash.zip](https://github.com/Iamsodarncool/TUNG/files/1647117/crash.zip)

No idea what happened here. I was alt-tabbed while googling for stuff and out of nowhere the crash dialog popped up.

I've attached a zip containing output_log.txt and the savefile.

*edit* oh wow I just tried to load the save back up and it's pretty corrupted.

**Comment by JimmyCushnie** [comment]
Can you upload that save file? If it had important stuff on it, the game automatically makes backups of your saves and you should be able to retrieve one of those.

**Comment by Shaolin-Funk** [comment]
Save file is in the zip, the link is at the top of the post.

**Comment by Shaolin-Funk** [comment]
Two things I need to mention as well: this crash occurred in version 0.1.3 and it hasn't happened since.

**Comment by JimmyCushnie** [comment]
probably fixed in 0.2
